//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Pedido
    {
        public string nombreDelCliente { get; set; }
        public string domicilioDeEntrega { get; set; }
        public string tipoDePedido { get; set; }
        public string estadoDelPedido { get; set; }
        public int idPedidos { get; set; }
        public int idProductos { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
