//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesPedido
    {
        public int idDetallesPedido { get; set; }
        public int Pedidos_idPedidos { get; set; }
        public int Empleados_idEmpleados { get; set; }
        public Nullable<System.DateTime> fechaHoraDelPedido { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Pedidos Pedidos { get; set; }
    }
}
