//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesPedido
    {
        public int idDetallesPedido { get; set; }
        public int Pedidos_idPedidos { get; set; }
        public Nullable<System.DateTime> fechaHoraDelPedido { get; set; }
        public int Empleados_idEmpleados { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Pedidos Pedidos { get; set; }
    }
}
