//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioDeInsumo
    {
        public int idInventarioDeInsumo { get; set; }
        public int Insumos_idInsumos { get; set; }
        public int Inventario_idInventario { get; set; }
        public Nullable<int> cantidadTotal { get; set; }
    
        public virtual Insumos Insumos { get; set; }
        public virtual Inventario Inventario { get; set; }
    }
}
