//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioDeProductos
    {
        public int idInventarioDeProductos { get; set; }
        public int Inventario_idInventario { get; set; }
        public int Productos_idProductos { get; set; }
        public Nullable<int> cantidadTotal { get; set; }
    
        public virtual Inventario Inventario { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
