//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizzaClient.ItaliaPizzaServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Productos", Namespace="http://schemas.datacontract.org/2004/07/Logic")]
    [System.SerializableAttribute()]
    public partial class Productos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoProducto {
            get {
                return this.CodigoProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoProductoField, value) != true)) {
                    this.CodigoProductoField = value;
                    this.RaisePropertyChanged("CodigoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProductos {
            get {
                return this.IdProductosField;
            }
            set {
                if ((this.IdProductosField.Equals(value) != true)) {
                    this.IdProductosField = value;
                    this.RaisePropertyChanged("IdProductos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Insumos", Namespace="http://schemas.datacontract.org/2004/07/Logic")]
    [System.SerializableAttribute()]
    public partial class Insumos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CantidadDeEmpaqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoInsumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdInsumosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CantidadDeEmpaque {
            get {
                return this.CantidadDeEmpaqueField;
            }
            set {
                if ((object.ReferenceEquals(this.CantidadDeEmpaqueField, value) != true)) {
                    this.CantidadDeEmpaqueField = value;
                    this.RaisePropertyChanged("CantidadDeEmpaque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoInsumo {
            get {
                return this.CodigoInsumoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoInsumoField, value) != true)) {
                    this.CodigoInsumoField = value;
                    this.RaisePropertyChanged("CodigoInsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdInsumos {
            get {
                return this.IdInsumosField;
            }
            set {
                if ((this.IdInsumosField.Equals(value) != true)) {
                    this.IdInsumosField = value;
                    this.RaisePropertyChanged("IdInsumos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleados", Namespace="http://schemas.datacontract.org/2004/07/Logic")]
    [System.SerializableAttribute()]
    public partial class Empleados : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEmpleadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpleados {
            get {
                return this.IdEmpleadosField;
            }
            set {
                if ((this.IdEmpleadosField.Equals(value) != true)) {
                    this.IdEmpleadosField = value;
                    this.RaisePropertyChanged("IdEmpleados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ItaliaPizzaServer.IProductManager")]
    public interface IProductManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManager/RegistrarProducto", ReplyAction="http://tempuri.org/IProductManager/RegistrarProductoResponse")]
        bool RegistrarProducto(ItaliaPizzaClient.ItaliaPizzaServer.Productos producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManager/RegistrarProducto", ReplyAction="http://tempuri.org/IProductManager/RegistrarProductoResponse")]
        System.Threading.Tasks.Task<bool> RegistrarProductoAsync(ItaliaPizzaClient.ItaliaPizzaServer.Productos producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManager/ProductoYaRegistrado", ReplyAction="http://tempuri.org/IProductManager/ProductoYaRegistradoResponse")]
        bool ProductoYaRegistrado(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManager/ProductoYaRegistrado", ReplyAction="http://tempuri.org/IProductManager/ProductoYaRegistradoResponse")]
        System.Threading.Tasks.Task<bool> ProductoYaRegistradoAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManager/ObtenerListaProductos", ReplyAction="http://tempuri.org/IProductManager/ObtenerListaProductosResponse")]
        ItaliaPizzaClient.ItaliaPizzaServer.Productos[] ObtenerListaProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManager/ObtenerListaProductos", ReplyAction="http://tempuri.org/IProductManager/ObtenerListaProductosResponse")]
        System.Threading.Tasks.Task<ItaliaPizzaClient.ItaliaPizzaServer.Productos[]> ObtenerListaProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManager/EliminarProducto", ReplyAction="http://tempuri.org/IProductManager/EliminarProductoResponse")]
        bool EliminarProducto(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManager/EliminarProducto", ReplyAction="http://tempuri.org/IProductManager/EliminarProductoResponse")]
        System.Threading.Tasks.Task<bool> EliminarProductoAsync(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManager/ActualizarProducto", ReplyAction="http://tempuri.org/IProductManager/ActualizarProductoResponse")]
        bool ActualizarProducto(int idProducto, string nombre, string codigoProducto, string marca, string tipo, double precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManager/ActualizarProducto", ReplyAction="http://tempuri.org/IProductManager/ActualizarProductoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarProductoAsync(int idProducto, string nombre, string codigoProducto, string marca, string tipo, double precio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductManagerChannel : ItaliaPizzaClient.ItaliaPizzaServer.IProductManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductManagerClient : System.ServiceModel.ClientBase<ItaliaPizzaClient.ItaliaPizzaServer.IProductManager>, ItaliaPizzaClient.ItaliaPizzaServer.IProductManager {
        
        public ProductManagerClient() {
        }
        
        public ProductManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegistrarProducto(ItaliaPizzaClient.ItaliaPizzaServer.Productos producto) {
            return base.Channel.RegistrarProducto(producto);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarProductoAsync(ItaliaPizzaClient.ItaliaPizzaServer.Productos producto) {
            return base.Channel.RegistrarProductoAsync(producto);
        }
        
        public bool ProductoYaRegistrado(string nombre) {
            return base.Channel.ProductoYaRegistrado(nombre);
        }
        
        public System.Threading.Tasks.Task<bool> ProductoYaRegistradoAsync(string nombre) {
            return base.Channel.ProductoYaRegistradoAsync(nombre);
        }
        
        public ItaliaPizzaClient.ItaliaPizzaServer.Productos[] ObtenerListaProductos() {
            return base.Channel.ObtenerListaProductos();
        }
        
        public System.Threading.Tasks.Task<ItaliaPizzaClient.ItaliaPizzaServer.Productos[]> ObtenerListaProductosAsync() {
            return base.Channel.ObtenerListaProductosAsync();
        }
        
        public bool EliminarProducto(int idProducto) {
            return base.Channel.EliminarProducto(idProducto);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarProductoAsync(int idProducto) {
            return base.Channel.EliminarProductoAsync(idProducto);
        }
        
        public bool ActualizarProducto(int idProducto, string nombre, string codigoProducto, string marca, string tipo, double precio) {
            return base.Channel.ActualizarProducto(idProducto, nombre, codigoProducto, marca, tipo, precio);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarProductoAsync(int idProducto, string nombre, string codigoProducto, string marca, string tipo, double precio) {
            return base.Channel.ActualizarProductoAsync(idProducto, nombre, codigoProducto, marca, tipo, precio);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ItaliaPizzaServer.IInsumoManager")]
    public interface IInsumoManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsumoManager/RegistrarInsumo", ReplyAction="http://tempuri.org/IInsumoManager/RegistrarInsumoResponse")]
        bool RegistrarInsumo(ItaliaPizzaClient.ItaliaPizzaServer.Insumos insumo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsumoManager/RegistrarInsumo", ReplyAction="http://tempuri.org/IInsumoManager/RegistrarInsumoResponse")]
        System.Threading.Tasks.Task<bool> RegistrarInsumoAsync(ItaliaPizzaClient.ItaliaPizzaServer.Insumos insumo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsumoManager/InsumoYaRegistrado", ReplyAction="http://tempuri.org/IInsumoManager/InsumoYaRegistradoResponse")]
        bool InsumoYaRegistrado(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsumoManager/InsumoYaRegistrado", ReplyAction="http://tempuri.org/IInsumoManager/InsumoYaRegistradoResponse")]
        System.Threading.Tasks.Task<bool> InsumoYaRegistradoAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsumoManager/ObtenerListaInsumos", ReplyAction="http://tempuri.org/IInsumoManager/ObtenerListaInsumosResponse")]
        ItaliaPizzaClient.ItaliaPizzaServer.Insumos[] ObtenerListaInsumos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsumoManager/ObtenerListaInsumos", ReplyAction="http://tempuri.org/IInsumoManager/ObtenerListaInsumosResponse")]
        System.Threading.Tasks.Task<ItaliaPizzaClient.ItaliaPizzaServer.Insumos[]> ObtenerListaInsumosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsumoManager/EliminarInsumo", ReplyAction="http://tempuri.org/IInsumoManager/EliminarInsumoResponse")]
        bool EliminarInsumo(int idInsumo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsumoManager/EliminarInsumo", ReplyAction="http://tempuri.org/IInsumoManager/EliminarInsumoResponse")]
        System.Threading.Tasks.Task<bool> EliminarInsumoAsync(int idInsumo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsumoManager/ActualizarInsumo", ReplyAction="http://tempuri.org/IInsumoManager/ActualizarInsumoResponse")]
        bool ActualizarInsumo(int idInsumo, string nombre, string codigoInsumo, string marca, string tipo, string cantidadDeEmpaque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsumoManager/ActualizarInsumo", ReplyAction="http://tempuri.org/IInsumoManager/ActualizarInsumoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarInsumoAsync(int idInsumo, string nombre, string codigoInsumo, string marca, string tipo, string cantidadDeEmpaque);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInsumoManagerChannel : ItaliaPizzaClient.ItaliaPizzaServer.IInsumoManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsumoManagerClient : System.ServiceModel.ClientBase<ItaliaPizzaClient.ItaliaPizzaServer.IInsumoManager>, ItaliaPizzaClient.ItaliaPizzaServer.IInsumoManager {
        
        public InsumoManagerClient() {
        }
        
        public InsumoManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InsumoManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsumoManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsumoManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegistrarInsumo(ItaliaPizzaClient.ItaliaPizzaServer.Insumos insumo) {
            return base.Channel.RegistrarInsumo(insumo);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarInsumoAsync(ItaliaPizzaClient.ItaliaPizzaServer.Insumos insumo) {
            return base.Channel.RegistrarInsumoAsync(insumo);
        }
        
        public bool InsumoYaRegistrado(string nombre) {
            return base.Channel.InsumoYaRegistrado(nombre);
        }
        
        public System.Threading.Tasks.Task<bool> InsumoYaRegistradoAsync(string nombre) {
            return base.Channel.InsumoYaRegistradoAsync(nombre);
        }
        
        public ItaliaPizzaClient.ItaliaPizzaServer.Insumos[] ObtenerListaInsumos() {
            return base.Channel.ObtenerListaInsumos();
        }
        
        public System.Threading.Tasks.Task<ItaliaPizzaClient.ItaliaPizzaServer.Insumos[]> ObtenerListaInsumosAsync() {
            return base.Channel.ObtenerListaInsumosAsync();
        }
        
        public bool EliminarInsumo(int idInsumo) {
            return base.Channel.EliminarInsumo(idInsumo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarInsumoAsync(int idInsumo) {
            return base.Channel.EliminarInsumoAsync(idInsumo);
        }
        
        public bool ActualizarInsumo(int idInsumo, string nombre, string codigoInsumo, string marca, string tipo, string cantidadDeEmpaque) {
            return base.Channel.ActualizarInsumo(idInsumo, nombre, codigoInsumo, marca, tipo, cantidadDeEmpaque);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarInsumoAsync(int idInsumo, string nombre, string codigoInsumo, string marca, string tipo, string cantidadDeEmpaque) {
            return base.Channel.ActualizarInsumoAsync(idInsumo, nombre, codigoInsumo, marca, tipo, cantidadDeEmpaque);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ItaliaPizzaServer.IUserManager")]
    public interface IUserManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/IniciarSesion", ReplyAction="http://tempuri.org/IUserManager/IniciarSesionResponse")]
        ItaliaPizzaClient.ItaliaPizzaServer.Empleados IniciarSesion(string correo, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/IniciarSesion", ReplyAction="http://tempuri.org/IUserManager/IniciarSesionResponse")]
        System.Threading.Tasks.Task<ItaliaPizzaClient.ItaliaPizzaServer.Empleados> IniciarSesionAsync(string correo, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/ExisteCorreoYContraseña", ReplyAction="http://tempuri.org/IUserManager/ExisteCorreoYContraseñaResponse")]
        bool ExisteCorreoYContraseña(string correo, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/ExisteCorreoYContraseña", ReplyAction="http://tempuri.org/IUserManager/ExisteCorreoYContraseñaResponse")]
        System.Threading.Tasks.Task<bool> ExisteCorreoYContraseñaAsync(string correo, string contraseña);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserManagerChannel : ItaliaPizzaClient.ItaliaPizzaServer.IUserManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagerClient : System.ServiceModel.ClientBase<ItaliaPizzaClient.ItaliaPizzaServer.IUserManager>, ItaliaPizzaClient.ItaliaPizzaServer.IUserManager {
        
        public UserManagerClient() {
        }
        
        public UserManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ItaliaPizzaClient.ItaliaPizzaServer.Empleados IniciarSesion(string correo, string contraseña) {
            return base.Channel.IniciarSesion(correo, contraseña);
        }
        
        public System.Threading.Tasks.Task<ItaliaPizzaClient.ItaliaPizzaServer.Empleados> IniciarSesionAsync(string correo, string contraseña) {
            return base.Channel.IniciarSesionAsync(correo, contraseña);
        }
        
        public bool ExisteCorreoYContraseña(string correo, string contraseña) {
            return base.Channel.ExisteCorreoYContraseña(correo, contraseña);
        }
        
        public System.Threading.Tasks.Task<bool> ExisteCorreoYContraseñaAsync(string correo, string contraseña) {
            return base.Channel.ExisteCorreoYContraseñaAsync(correo, contraseña);
        }
    }
}
